services:
  - type: web
    name: pravallika-portfolio-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
